CREATE TABLE Vokabeln (
 vokabel_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT;
 norwegisch   VARCHAR(64),
 deutsch   VARCHAR(64),
 anmerkung  VARCHAR(64),
 kapitelnr  INTEGER,
 wortart   VARCHAR(32)
);